	var Segunda10 = "Marlbo0ro ";
	var Segunda11 = "Marcio_oliver ";
	var Segunda12 = "Maaydaambros ";
	var Segunda13 = "Tmacumba ";
	var Segunda14 = "Lowquez ";
	var Segunda15 = "Antonioparehtv ";
	var Segunda16 = "Kitterstv ";
	var Segunda17 = "dreads312 ";
	var Segunda18 = "instagiaria ";
	var Segunda19 = "nazmysoares ";
	var Segunda20 = "Renanzero ";
	var Segunda21 = "Mistergameroficial";
	var Segunda22 = "slyferin ";
	var Segunda23 = "Kaledotv";
	
	var Terca10 = "Marlbo0ro ";
	var Terca11 = "Marcio_oliver ";
	var Terca12 = "Maaydaambros ";
	var Terca13 = "Tmacumba ";
	var Terca14 = "Lowquez ";
	var Terca15 = "Antonioparehtv ";
	var Terca16 = "Kitterstv ";
	var Terca17 = "dreads312 ";
	var Terca18 = "instagiaria ";
	var Terca19 = "nazmysoares ";
	var Terca20 = "Renanzero ";
	var Terca21 = "Mistergameroficial";
	var Terca22 = "slyferin ";
	var Terca23 = "Kaledotv";	
	
	var Quarta10 = "Marlbo0ro ";
	var Quarta11 = "Marcio_oliver ";
	var Quarta12 = "Maaydaambros ";
	var Quarta13 = "Tmacumba ";
	var Quarta14 = "Lowquez ";
	var Quarta15 = "Antonioparehtv ";
	var Quarta16 = "Kitterstv ";
	var Quarta17 = "dreads312 ";
	var Quarta18 = "instagiaria ";
	var Quarta19 = "nazmysoares ";
	var Quarta20 = "Renanzero ";
	var Quarta21 = "Mistergameroficial";
	var Quarta22 = "slyferin ";
	var Quarta23 = "Kaledotv";
	
	var Quinta10 = "Marlbo0ro ";
	var Quinta11 = "Marcio_oliver ";
	var Quinta12 = "Maaydaambros ";
	var Quinta13 = "Tmacumba ";
	var Quinta14 = "Lowquez ";
	var Quinta15 = "Antonioparehtv ";
	var Quinta16 = "Kitterstv ";
	var Quinta17 = "dreads312 ";
	var Quinta18 = "instagiaria ";
	var Quinta19 = "nazmysoares ";
	var Quinta20 = "Renanzero ";
	var Quinta21 = "Mistergameroficial";
	var Quinta22 = "slyferin ";
	var Quinta23 = "Kaledotv";
	
	var Sexta10 = "Marlbo0ro ";
	var Sexta11 = "Marcio_oliver ";
	var Sexta12 = "Maaydaambros ";
	var Sexta13 = "Tmacumba ";
	var Sexta14 = "Lowquez ";
	var Sexta15 = "Antonioparehtv ";
	var Sexta16 = "Kitterstv ";
	var Sexta17 = "dreads312 ";
	var Sexta18 = "instagiaria ";
	var Sexta19 = "nazmysoares ";
	var Sexta20 = "Renanzero ";
	var Sexta21 = "Mistergameroficial";
	var Sexta22 = "slyferin ";
	var Sexta23 = "Kaledotv";
	
	var Sabado10 = "Marlbo0ro ";
	var Sabado11 = "Marcio_oliver ";
	var Sabado12 = "Maaydaambros ";
	var Sabado13 = "Tmacumba ";
	var Sabado14 = "Lowquez ";
	var Sabado15 = "Antonioparehtv ";
	var Sabado16 = "Kitterstv ";
	var Sabado17 = "dreads312 ";
	var Sabado18 = "instagiaria ";
	var Sabado19 = "nazmysoares ";
	var Sabado20 = "Renanzero ";
	var Sabado21 = "Mistergameroficial";
	var Sabado22 = "slyferin ";
	var Sabado23 = "Kaledotv";
	
	document.getElementById("Segunda10").innerHTML = "<a href='http://twitch.tv/" + Segunda10 + "' target='_blank'>" + Segunda10 + "</a>";
	document.getElementById("Segunda11").innerHTML = "<a href='http://twitch.tv/" + Segunda11 + "' target='_blank'>" + Segunda11 + "</a>";
	document.getElementById("Segunda12").innerHTML = "<a href='http://twitch.tv/" + Segunda12 + "' target='_blank'>" + Segunda12 + "</a>";
	document.getElementById("Segunda13").innerHTML = "<a href='http://twitch.tv/" + Segunda13 + "' target='_blank'>" + Segunda13 + "</a>";
	document.getElementById("Segunda14").innerHTML = "<a href='http://twitch.tv/" + Segunda14 + "' target='_blank'>" + Segunda14 + "</a>";
	document.getElementById("Segunda15").innerHTML = "<a href='http://twitch.tv/" + Segunda15 + "' target='_blank'>" + Segunda15 + "</a>";
	document.getElementById("Segunda16").innerHTML = "<a href='http://twitch.tv/" + Segunda16 + "' target='_blank'>" + Segunda16 + "</a>";
	document.getElementById("Segunda17").innerHTML = "<a href='http://twitch.tv/" + Segunda17 + "' target='_blank'>" + Segunda17 + "</a>";
	document.getElementById("Segunda18").innerHTML = "<a href='http://twitch.tv/" + Segunda18 + "' target='_blank'>" + Segunda18 + "</a>";
	document.getElementById("Segunda19").innerHTML = "<a href='http://twitch.tv/" + Segunda19 + "' target='_blank'>" + Segunda19 + "</a>";
	document.getElementById("Segunda20").innerHTML = "<a href='http://twitch.tv/" + Segunda20 + "' target='_blank'>" + Segunda20 + "</a>";
	document.getElementById("Segunda21").innerHTML = "<a href='http://twitch.tv/" + Segunda21 + "' target='_blank'>" + Segunda21 + "</a>";
	document.getElementById("Segunda22").innerHTML = "<a href='http://twitch.tv/" + Segunda22 + "' target='_blank'>" + Segunda22 + "</a>";
	document.getElementById("Segunda23").innerHTML = "<a href='http://twitch.tv/" + Segunda23 + "' target='_blank'>" + Segunda23 + "</a>";
	document.getElementById("Terca10").innerHTML = "<a href='http://twitch.tv/" + Terca10 + "' target='_blank'>" + Terca10 + "</a>";
	document.getElementById("Terca11").innerHTML = "<a href='http://twitch.tv/" + Terca11 + "' target='_blank'>" + Terca11 + "</a>";
	document.getElementById("Terca12").innerHTML = "<a href='http://twitch.tv/" + Terca12 + "' target='_blank'>" + Terca12 + "</a>";
	document.getElementById("Terca13").innerHTML = "<a href='http://twitch.tv/" + Terca13 + "' target='_blank'>" + Terca13 + "</a>";
	document.getElementById("Terca14").innerHTML = "<a href='http://twitch.tv/" + Terca14 + "' target='_blank'>" + Terca14 + "</a>";
	document.getElementById("Terca15").innerHTML = "<a href='http://twitch.tv/" + Terca15 + "' target='_blank'>" + Terca15 + "</a>";
	document.getElementById("Terca16").innerHTML = "<a href='http://twitch.tv/" + Terca16 + "' target='_blank'>" + Terca16 + "</a>";
	document.getElementById("Terca17").innerHTML = "<a href='http://twitch.tv/" + Terca17 + "' target='_blank'>" + Terca17 + "</a>";
	document.getElementById("Terca18").innerHTML = "<a href='http://twitch.tv/" + Terca18 + "' target='_blank'>" + Terca18 + "</a>";
	document.getElementById("Terca19").innerHTML = "<a href='http://twitch.tv/" + Terca19 + "' target='_blank'>" + Terca19 + "</a>";
	document.getElementById("Terca20").innerHTML = "<a href='http://twitch.tv/" + Terca20 + "' target='_blank'>" + Terca20 + "</a>";
	document.getElementById("Terca21").innerHTML = "<a href='http://twitch.tv/" + Terca21 + "' target='_blank'>" + Terca21 + "</a>";
	document.getElementById("Terca22").innerHTML = "<a href='http://twitch.tv/" + Terca22 + "' target='_blank'>" + Terca22 + "</a>";
	document.getElementById("Terca23").innerHTML = "<a href='http://twitch.tv/" + Terca23 + "' target='_blank'>" + Terca23 + "</a>";
	document.getElementById("Quarta10").innerHTML = "<a href='http://twitch.tv/" + Quarta10 + "' target='_blank'>" + Quarta10 + "</a>";
	document.getElementById("Quarta11").innerHTML = "<a href='http://twitch.tv/" + Quarta11 + "' target='_blank'>" + Quarta11 + "</a>";
	document.getElementById("Quarta12").innerHTML = "<a href='http://twitch.tv/" + Quarta12 + "' target='_blank'>" + Quarta12 + "</a>";
	document.getElementById("Quarta13").innerHTML = "<a href='http://twitch.tv/" + Quarta13 + "' target='_blank'>" + Quarta13 + "</a>";
	document.getElementById("Quarta14").innerHTML = "<a href='http://twitch.tv/" + Quarta14 + "' target='_blank'>" + Quarta14 + "</a>";
	document.getElementById("Quarta15").innerHTML = "<a href='http://twitch.tv/" + Quarta15 + "' target='_blank'>" + Quarta15 + "</a>";
	document.getElementById("Quarta16").innerHTML = "<a href='http://twitch.tv/" + Quarta16 + "' target='_blank'>" + Quarta16 + "</a>";
	document.getElementById("Quarta17").innerHTML = "<a href='http://twitch.tv/" + Quarta17 + "' target='_blank'>" + Quarta17 + "</a>";
	document.getElementById("Quarta18").innerHTML = "<a href='http://twitch.tv/" + Quarta18 + "' target='_blank'>" + Quarta18 + "</a>";
	document.getElementById("Quarta19").innerHTML = "<a href='http://twitch.tv/" + Quarta19 + "' target='_blank'>" + Quarta19 + "</a>";
	document.getElementById("Quarta20").innerHTML = "<a href='http://twitch.tv/" + Quarta20 + "' target='_blank'>" + Quarta20 + "</a>";
	document.getElementById("Quarta21").innerHTML = "<a href='http://twitch.tv/" + Quarta21 + "' target='_blank'>" + Quarta21 + "</a>";
	document.getElementById("Quarta22").innerHTML = "<a href='http://twitch.tv/" + Quarta22 + "' target='_blank'>" + Quarta22 + "</a>";
	document.getElementById("Quarta23").innerHTML = "<a href='http://twitch.tv/" + Quarta23 + "' target='_blank'>" + Quarta23 + "</a>";
	document.getElementById("Quinta10").innerHTML = "<a href='http://twitch.tv/" + Quinta10 + "' target='_blank'>" + Quinta10 + "</a>";
	document.getElementById("Quinta11").innerHTML = "<a href='http://twitch.tv/" + Quinta11 + "' target='_blank'>" + Quinta11 + "</a>";
	document.getElementById("Quinta12").innerHTML = "<a href='http://twitch.tv/" + Quinta12 + "' target='_blank'>" + Quinta12 + "</a>";
	document.getElementById("Quinta13").innerHTML = "<a href='http://twitch.tv/" + Quinta13 + "' target='_blank'>" + Quinta13 + "</a>";
	document.getElementById("Quinta14").innerHTML = "<a href='http://twitch.tv/" + Quinta14 + "' target='_blank'>" + Quinta14 + "</a>";
	document.getElementById("Quinta15").innerHTML = "<a href='http://twitch.tv/" + Quinta15 + "' target='_blank'>" + Quinta15 + "</a>";
	document.getElementById("Quinta16").innerHTML = "<a href='http://twitch.tv/" + Quinta16 + "' target='_blank'>" + Quinta16 + "</a>";
	document.getElementById("Quinta17").innerHTML = "<a href='http://twitch.tv/" + Quinta17 + "' target='_blank'>" + Quinta17 + "</a>";
	document.getElementById("Quinta18").innerHTML = "<a href='http://twitch.tv/" + Quinta18 + "' target='_blank'>" + Quinta18 + "</a>";
	document.getElementById("Quinta19").innerHTML = "<a href='http://twitch.tv/" + Quinta19 + "' target='_blank'>" + Quinta19 + "</a>";
	document.getElementById("Quinta20").innerHTML = "<a href='http://twitch.tv/" + Quinta20 + "' target='_blank'>" + Quinta20 + "</a>";
	document.getElementById("Quinta21").innerHTML = "<a href='http://twitch.tv/" + Quinta21 + "' target='_blank'>" + Quinta21 + "</a>";
	document.getElementById("Quinta22").innerHTML = "<a href='http://twitch.tv/" + Quinta22 + "' target='_blank'>" + Quinta22 + "</a>";
	document.getElementById("Quinta23").innerHTML = "<a href='http://twitch.tv/" + Quinta23 + "' target='_blank'>" + Quinta23 + "</a>";
	document.getElementById("Sexta10").innerHTML = "<a href='http://twitch.tv/" + Sexta10 + "' target='_blank'>" + Sexta10 + "</a>";
	document.getElementById("Sexta11").innerHTML = "<a href='http://twitch.tv/" + Sexta11 + "' target='_blank'>" + Sexta11 + "</a>";
	document.getElementById("Sexta12").innerHTML = "<a href='http://twitch.tv/" + Sexta12 + "' target='_blank'>" + Sexta12 + "</a>";
	document.getElementById("Sexta13").innerHTML = "<a href='http://twitch.tv/" + Sexta13 + "' target='_blank'>" + Sexta13 + "</a>";
	document.getElementById("Sexta14").innerHTML = "<a href='http://twitch.tv/" + Sexta14 + "' target='_blank'>" + Sexta14 + "</a>";
	document.getElementById("Sexta15").innerHTML = "<a href='http://twitch.tv/" + Sexta15 + "' target='_blank'>" + Sexta15 + "</a>";
	document.getElementById("Sexta16").innerHTML = "<a href='http://twitch.tv/" + Sexta16 + "' target='_blank'>" + Sexta16 + "</a>";
	document.getElementById("Sexta17").innerHTML = "<a href='http://twitch.tv/" + Sexta17 + "' target='_blank'>" + Sexta17 + "</a>";
	document.getElementById("Sexta18").innerHTML = "<a href='http://twitch.tv/" + Sexta18 + "' target='_blank'>" + Sexta18 + "</a>";
	document.getElementById("Sexta19").innerHTML = "<a href='http://twitch.tv/" + Sexta19 + "' target='_blank'>" + Sexta19 + "</a>";
	document.getElementById("Sexta20").innerHTML = "<a href='http://twitch.tv/" + Sexta20 + "' target='_blank'>" + Sexta20 + "</a>";
	document.getElementById("Sexta21").innerHTML = "<a href='http://twitch.tv/" + Sexta21 + "' target='_blank'>" + Sexta21 + "</a>";
	document.getElementById("Sexta22").innerHTML = "<a href='http://twitch.tv/" + Sexta22 + "' target='_blank'>" + Sexta22 + "</a>";
	document.getElementById("Sexta23").innerHTML = "<a href='http://twitch.tv/" + Sexta23 + "' target='_blank'>" + Sexta23 + "</a>";
	document.getElementById("Sabado10").innerHTML = "<a href='http://twitch.tv/" + Sabado10 + "' target='_blank'>" + Sabado10 + "</a>";
	document.getElementById("Sabado11").innerHTML = "<a href='http://twitch.tv/" + Sabado11 + "' target='_blank'>" + Sabado11 + "</a>";
	document.getElementById("Sabado12").innerHTML = "<a href='http://twitch.tv/" + Sabado12 + "' target='_blank'>" + Sabado12 + "</a>";
	document.getElementById("Sabado13").innerHTML = "<a href='http://twitch.tv/" + Sabado13 + "' target='_blank'>" + Sabado13 + "</a>";
	document.getElementById("Sabado14").innerHTML = "<a href='http://twitch.tv/" + Sabado14 + "' target='_blank'>" + Sabado14 + "</a>";
	document.getElementById("Sabado15").innerHTML = "<a href='http://twitch.tv/" + Sabado15 + "' target='_blank'>" + Sabado15 + "</a>";
	document.getElementById("Sabado16").innerHTML = "<a href='http://twitch.tv/" + Sabado16 + "' target='_blank'>" + Sabado16 + "</a>";
	document.getElementById("Sabado17").innerHTML = "<a href='http://twitch.tv/" + Sabado17 + "' target='_blank'>" + Sabado17 + "</a>";
	document.getElementById("Sabado18").innerHTML = "<a href='http://twitch.tv/" + Sabado18 + "' target='_blank'>" + Sabado18 + "</a>";
	document.getElementById("Sabado19").innerHTML = "<a href='http://twitch.tv/" + Sabado19 + "' target='_blank'>" + Sabado19 + "</a>";
	document.getElementById("Sabado20").innerHTML = "<a href='http://twitch.tv/" + Sabado20 + "' target='_blank'>" + Sabado20 + "</a>";
	document.getElementById("Sabado21").innerHTML = "<a href='http://twitch.tv/" + Sabado21 + "' target='_blank'>" + Sabado21 + "</a>";
	document.getElementById("Sabado22").innerHTML = "<a href='http://twitch.tv/" + Sabado22 + "' target='_blank'>" + Sabado22 + "</a>";
	document.getElementById("Sabado23").innerHTML = "<a href='http://twitch.tv/" + Sabado23 + "' target='_blank'>" + Sabado23 + "</a>";